services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    networks: [banka]

networks:
  banka:
    name: banka-net
    external: true
